# Vectorization Examples

# Import necessary libraries

In [1]:
import numpy as np
import math
import time

# Set Array & List Sizes

In [2]:
size = 1000000

# Set Number of Tests

In [3]:
num_tests = 5

# Creation: List vs Array

In [4]:
#NumPy array creation
tot_time = 0
for j in range(0,num_tests):
    # calculating execution time 
    initialTime = time.time()
    x_array = np.arange(size, dtype='float')
    t1 = time.time() - initialTime
    tot_time += t1
    #print(tot_time)
arr_time = tot_time/num_tests 
print("Average time taken using NumPy:",
      (arr_time),
      "seconds")

#Pyton list creation
tot_time = 0
for j in range(0,num_tests):
    # calculating execution time
    initialTime = time.time()
    x_list = []
    for i in range(0,size):
        x_list.append(float(i)) 
    t1 = time.time() - initialTime
    tot_time += t1
    #print(tot_time)
list_time = tot_time/num_tests  
print("Average time taken using Python list:",
      (list_time),
      "seconds")

print('NumPy speed increase factor of',list_time/arr_time)

print(x_array[0:10])
print(x_list[0:10])

Average time taken using NumPy: 0.00779576301574707 seconds
Average time taken using Python list: 0.565802526473999 seconds
NumPy speed increase factor of 72.57821015481163
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]


# Scalar Addition: NumPy vs 'for' loop

In [5]:
a = np.arange(size, dtype='float')

#NumPy array scalar addition
tot_time = 0
for j in range(0,num_tests):
    # calculating execution time 
    initialTime = time.time()
    c_np = a + 3.21
    t1 = time.time() - initialTime
    tot_time += t1
    #print(tot_time)
np_time = tot_time/num_tests 
print("Average time taken using NumPy:",
      (np_time),
      "seconds")

#Pyton for loop array addition
tot_time = 0
for j in range(0,num_tests):
    c_for = np.zeros(size, dtype='float')
    # calculating execution time
    initialTime = time.time()
    for i in range(0,size):
        c_for[i] = a[i] + 3.21 
    t1 = time.time() - initialTime
    tot_time += t1
    #print(tot_time)
for_time = tot_time/num_tests  
print("Average time taken using for loop:",
      (for_time),
      "seconds")

print('NumPy speed increase factor of',for_time/np_time)

print(c_np[0:10])
print(c_for[0:10])

Average time taken using NumPy: 0.009194231033325196 seconds
Average time taken using for loop: 0.7115009784698486 seconds
NumPy speed increase factor of 77.38558840766115
[ 3.21  4.21  5.21  6.21  7.21  8.21  9.21 10.21 11.21 12.21]
[ 3.21  4.21  5.21  6.21  7.21  8.21  9.21 10.21 11.21 12.21]


# Array Addition: NumPy vs 'for' loop

In [6]:
a = np.arange(size, dtype='float')
b = np.arange(size, dtype='float')

#NumPy array addition
tot_time = 0
for j in range(0,num_tests):
    # calculating execution time 
    initialTime = time.time()
    c_np = np.add(a,b)
    t1 = time.time() - initialTime
    tot_time += t1
    #print(tot_time)
np_time = tot_time/num_tests 
print("Average time taken using NumPy:",
      (np_time),
      "seconds")

#Pyton for loop array addition
tot_time = 0
for j in range(0,num_tests):
    c_for = np.zeros(size)
    # calculating execution time
    initialTime = time.time()
    for i in range(0,size):
        c_for[i] = a[i] + b[i] 
    t1 = time.time() - initialTime
    tot_time += t1
    #print(tot_time)
for_time = tot_time/num_tests  
print("Average time taken using for loop:",
      (for_time),
      "seconds")

print('NumPy speed increase factor of',for_time/np_time)

print(c_np[0:10])
print(c_for[0:10])

Average time taken using NumPy: 0.00939474105834961 seconds
Average time taken using for loop: 1.135395097732544 seconds
NumPy speed increase factor of 120.85432591284223
[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]
[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]


# Scalar Multiplication

In [7]:
a = np.arange(size, dtype='float')

#NumPy array scalar multiplication
tot_time = 0
for j in range(0,num_tests):
    # calculating execution time 
    initialTime = time.time()
    c_np = 5.2 * a
    t1 = time.time() - initialTime
    tot_time += t1
    #print(tot_time)
np_time = tot_time/num_tests 
print("Average time taken using NumPy:",
      (np_time),
      "seconds")

#Pyton for loop array scalar multiplication
tot_time = 0
for j in range(0,num_tests):
    c_for = np.zeros(size, dtype='float')
    # calculating execution time
    initialTime = time.time()
    for i in range(0,size):
        c_for[i] = 5.2 * a[i] 
    t1 = time.time() - initialTime
    tot_time += t1
    #print(tot_time)
for_time = tot_time/num_tests  
print("Average time taken using for loop:",
      (for_time),
      "seconds")

print('NumPy speed increase factor of',for_time/np_time)

print(c_np[0:10])
print(c_for[0:10])

Average time taken using NumPy: 0.009594058990478516 seconds
Average time taken using for loop: 0.707029390335083 seconds
NumPy speed increase factor of 73.69450104869733
[ 0.   5.2 10.4 15.6 20.8 26.  31.2 36.4 41.6 46.8]
[ 0.   5.2 10.4 15.6 20.8 26.  31.2 36.4 41.6 46.8]


# Array Multiplication: NumPy vs 'for' loop

In [8]:
a = np.arange(size, dtype='float')
b = np.arange(size, dtype='float')

#NumPy array addition
tot_time = 0
for j in range(0,num_tests):
    # calculating execution time 
    initialTime = time.time()
    c_np = a * b
    t1 = time.time() - initialTime
    tot_time += t1
    #print(tot_time)
np_time = tot_time/num_tests 
print("Average time taken using NumPy:",
      (np_time),
      "seconds")

#Pyton for loop array addition
tot_time = 0
for j in range(0,num_tests):
    c_for = np.zeros(size, dtype='float')
    # calculating execution time
    initialTime = time.time()
    for i in range(0,size):
        c_for[i] = a[i] * b[i] 
    t1 = time.time() - initialTime
    tot_time += t1
    #print(tot_time)
for_time = tot_time/num_tests  
print("Average time taken using for loop:",
      (for_time),
      "seconds")

print('NumPy speed increase factor of',for_time/np_time)

print(c_np[0:10])
print(c_for[0:10])

Average time taken using NumPy: 0.045017576217651366 seconds
Average time taken using for loop: 0.9997753620147705 seconds
NumPy speed increase factor of 22.208555991132172
[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]
[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]


# Applying a Function: NumPy vs 'for' loop

In [10]:
a = np.arange(size, dtype='float')

#NumPy array apply exponential function to all array elements
tot_time = 0
for j in range(0,num_tests):
    # calculating execution time 
    initialTime = time.time()
    c_np = np.sin(a)
    t1 = time.time() - initialTime
    tot_time += t1
    #print(tot_time)
np_time = tot_time/num_tests 
print("Average time taken using NumPy:",
      (np_time),
      "seconds")

#Pyton for loop apply exponential function to all array elements
tot_time = 0
for j in range(0,num_tests):
    c_for = np.zeros(size, dtype='float')
    # calculating execution time
    initialTime = time.time()
    for i in range(0,size):
        c_for[i] =  np.sin(a[i]) # could use math.sin(a[i]) to avoid NumPy confusion
    t1 = time.time() - initialTime
    tot_time += t1
    #print(tot_time)
for_time = tot_time/num_tests  
print("Average time taken using for loop:",
      (for_time),
      "seconds")

print('NumPy speed increase factor of',for_time/np_time)

print(c_np[0:10])
print(c_for[0:10])

Average time taken using NumPy: 0.03549714088439941 seconds
Average time taken using for loop: 2.85101900100708 seconds
NumPy speed increase factor of 80.3168629916352
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
